### ISSUE TITLE
Configuration for triggering digital_bookplate_instances DAG is passing trigger_execution_date_iso

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1281]
On a [recent test of the fetch_digital_bookplates DAG](https://sul-libsys-airflow-dev.stanford.edu/dags/fetch_digital_bookplates/grid?dag_run_id=manual__2024-10-15T19%3A49%3A13.248149%2B00%3A00&task_id=trigger_instances_dag), when it triggers the digital_bookplate_instances DAG, the following configuration is passed:
```
trigger_execution_date_iso: 2024-10-15T20:30:34.438675+00:00
trigger_run_id: manual__2024-10-15T20:30:34.438675+00:00
```
The trigger_instances_task using logical_date is still not passing to the next DAG correctly. It looks like the value of trigger_execution_date_iso is ending up in dag run logical date instead of what is defined here: https://github.com/sul-dlss/libsys-airflow/blob/da15bc128c0321f4ecf20ff722b54c825b1d68a3/libsys_airflow/plugins/digital_bookplates/purl_fetcher.py#L175C36-L175C59

In the [log for invoices_paid_within_date_range task](https://sul-libsys-airflow-dev.stanford.edu/dags/digital_bookplate_instances/grid?run_state=failed&dag_run_id=manual__2024-10-15T20%3A29%3A30.815908%2B00%3A00&task_id=invoices_paid_within_date_range&tab=logs), it shows:
```
[2024-10-15, 20:39:50 UTC] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: digital_bookplate_instances.invoices_paid_within_date_range manual__2024-10-15T20:29:30.815908+00:00 [queued]>
[2024-10-15, 20:39:50 UTC] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: digital_bookplate_instances.invoices_paid_within_date_range manual__2024-10-15T20:29:30.815908+00:00 [queued]>
[2024-10-15, 20:39:50 UTC] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-10-15, 20:39:50 UTC] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): invoices_paid_within_date_range> on 2024-10-15 20:29:30.815908+00:00
[2024-10-15, 20:39:50 UTC] {standard_task_runner.py:60} INFO - Started process 31466 to run task
[2024-10-15, 20:39:50 UTC] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'digital_bookplate_instances', 'invoices_paid_within_date_range', 'manual__2024-10-15T20:29:30.815908+00:00', '--job-id', '39629', '--raw', '--subdir', 'DAGS_FOLDER/digital_bookplates/digital_bookplate_instances.py', '--cfg-path', '/tmp/tmpsdcvbmyk']
[2024-10-15, 20:39:50 UTC] {standard_task_runner.py:88} INFO - Job 39629: Subtask invoices_paid_within_date_range
[2024-10-15, 20:39:50 UTC] {task_command.py:423} INFO - Running <TaskInstance: digital_bookplate_instances.invoices_paid_within_date_range manual__2024-10-15T20:29:30.815908+00:00 [running]> on host a2549177c8c5
[2024-10-15, 20:39:50 UTC] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='libsys' AIRFLOW_CTX_DAG_ID='digital_bookplate_instances' AIRFLOW_CTX_TASK_ID='invoices_paid_within_date_range' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T20:29:30.815908+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T20:29:30.815908+00:00'
[2024-10-15, 20:39:50 UTC] {_client.py:1038} INFO - HTTP Request: POST https://okapi-test.stanford.edu/authn/login-with-expiry "HTTP/1.1 201 Created"
[2024-10-15, 20:39:50 UTC] {invoices.py:123} INFO - Querying paid invoices with paymentDate >= 2024-10-02 09:00:00+00:00
[2024-10-15, 20:39:50 UTC] {_client.py:1038} INFO - HTTP Request: GET https://okapi-test.stanford.edu/invoice-storage/invoices?query=%28%28paymentDate%3E%3D2024-10-15%2020%3A29%3A30.815908%2B00%3A00%29%20and%20status%3D%3D%22Paid%22%29&limit=500&offset=0 "HTTP/1.1 400 Bad Request"
[2024-10-15, 20:39:50 UTC] {taskinstance.py:2731} ERROR - Task failed with exception
<snip>
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://okapi-test.stanford.edu/invoice-storage/invoices?query=%28%28paymentDate%3E%3D2024-10-15%2020%3A29%3A30.815908%2B00%3A00%29%20and%20status%3D%3D%22Paid%22%29&limit=500&offset=0'
```
The invoices_paid_within_date_range should be getting the from_date query parameter from the dag run's logical_date, see https://github.com/sul-dlss/libsys-airflow/blob/da15bc128c0321f4ecf20ff722b54c825b1d68a3/libsys_airflow/plugins/folio/invoices.py#L122-L125

The logging info on line 122 should be below the from_date being set via dag run's logical_date (it currently is reporting the from_date using the dag run's data_interval_start.

Maybe the invoices_paid_within_date_range should use trigger_execution_date_iso instead?

**Comment by shelleydoljack** [comment]
When triggering the digital_bookplate_instances DAG in the UI with date 2023-08-28 T00:00:00, the invoices_paid_within_date_range task shows this date param in the log:
```
[2024-10-15, 21:21:32 UTC] {invoices.py:123} INFO - Querying paid invoices with paymentDate >= 2023-08-16 09:00:00+00:00
```
Also, the number of invoices is greater than the XComArg length, so the task fails:
```
[2024-10-15, 21:21:35 UTC] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 452, in _execute_task
    _record_task_map_for_downstreams(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 932, in _record_task_map_for_downstreams
    raise UnmappableXComLengthPushed(value, max_map_length)
airflow.exceptions.UnmappableXComLengthPushed: unmappable return value length: 10537 > 1024
```
So even if we get the logical_date param sorted out from the fetch_digital_bookplates DAG to the digital_bookplates_instances DAG, we will end up with this issue of too many invoices from 2023-08-28. We need to refactor this in some way. One thought, from #1273 is to reconsider the DAG schedule. When trying to run the DAG with a from_date of 8/28/2023, maybe the DAG definition should have catchup=True in order to spawn many DAG runs with only weekly paymentDate ranges.

**Comment by shelleydoljack** [comment]
Another thought is to make the invoices_paid_within_date_range a task group as well. And then we don't have to futz with the catchup dag runs. 🤷

**Comment by shelleydoljack** [comment]
Using swagger UI to query the airflow db, for one of the dag runs that was kicked off by fetch_digital_bookplates, here is the data:
```
curl -X 'GET' \
  'https://sul-libsys-airflow-dev.stanford.edu/api/v1/dags/digital_bookplate_instances/dagRuns/manual__2024-10-15T20%3A29%3A28.568742%2B00%3A00' \
  -H 'accept: application/json'
{
  "conf": {
    "funds": {
      "db_id": 1687,
      "druid": "bt942vy4674",
      "failure": null,
      "fund_name": null,
      "fund_uuid": null,
      "image_filename": "bt942vy4674_00_0001.jp2",
      "title": "Stanford Law Library in Memory of Henry Vrooman"
    },
    "logical_date": "2023-08-28T00:00:00+00:00"
  },
  "dag_id": "digital_bookplate_instances",
  "dag_run_id": "manual__2024-10-15T20:29:28.568742+00:00",
  "data_interval_end": "2024-10-09T09:00:00+00:00",
  "data_interval_start": "2024-10-02T09:00:00+00:00",
  "end_date": "2024-10-15T20:32:54.450797+00:00",
  "execution_date": "2024-10-15T20:29:28.568742+00:00",
  "external_trigger": true,
  "last_scheduling_decision": "2024-10-15T20:32:54.448470+00:00",
  "logical_date": "2024-10-15T20:29:28.568742+00:00",
  "note": null,
  "run_type": "manual",
  "start_date": "2024-10-15T20:29:29.049825+00:00",
  "state": "failed"
}
```
Maybe we just hardcode the start date or pull it from the dag config.

**Comment by shelleydoljack** [comment]
Hmm, this is still not right somehow. On the latest [run](https://sul-libsys-airflow-dev.stanford.edu/dags/fetch_digital_bookplates/grid?dag_run_id=scheduled__2024-10-09T14%3A00%3A00%2B00%3A00&task_id=trigger_instances_dag&tab=logs):
```
[2024-10-16, 21:46:05 UTC] {purl_fetcher.py:171} ERROR - Should trigger 841 DAG runs
[2024-10-16, 21:46:05 UTC] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/libsys_airflow/plugins/digital_bookplates/purl_fetcher.py", line 173, in trigger_instances_dag
    TriggerDagRunOperator(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/trigger_dagrun.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to TriggerDagRunOperator (task_id: new-instance-dag-0). Invalid arguments were:
**kwargs: {'logical_date': '2023-08-28T00:00:00+00:00'}
[2024-10-16, 21:46:05 UTC] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=fetch_digital_bookplates, task_id=trigger_instances_dag, execution_date=20241009T140000, start_date=20241016T214604, end_date=20241016T214605
[2024-10-16, 21:46:05 UTC] {standard_task_runner.py:107} ERROR - Failed to execute job 41435 for task trigger_instances_dag (Invalid arguments were passed to TriggerDagRunOperator (task_id: new-instance-dag-0). Invalid arguments were:
**kwargs: {'logical_date': '2023-08-28T00:00:00+00:00'}; 28705)
[2024-10-16, 21:46:05 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 1
```

**Comment by shelleydoljack** [comment]
Ugh, so it IS supposed to be execution_date I guess: https://airflow.apache.org/docs/apache-airflow/2.8.3/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator
or in conf like it was but downstream tasks aren't looking in conf.

**Comment by shelleydoljack** [comment]
Hmm, but if we use execution_date, then the trigger_dag_id will be set to the same thing for each and that won't work either. See [airflow docs source code](https://airflow.apache.org/docs/apache-airflow/2.8.3/_modules/airflow/operators/trigger_dagrun.html#TriggerDagRunOperator.execute):
```
if self.trigger_run_id:
            run_id = str(self.trigger_run_id)
        else:
            run_id = DagRun.generate_run_id(DagRunType.MANUAL, parsed_execution_date)
```
When run locally, I see in the log:
```
    raise DagRunAlreadyExists(dag_run=dag_run, execution_date=execution_date, run_id=run_id)
airflow.exceptions.DagRunAlreadyExists: A DAG Run already exists for DAG digital_bookplate_instances at 2023-08-28T00:00:00+00:00 with run id manual__2023-08-28T00:00:00+00:00
```
So we probably want to go back to using conf.
