### ISSUE TITLE
Too many invoice lines causes UnmappableXComLengthPushed exception

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1335]
On a recent test run for getting all the paid invoice lines for a new bookplate fund, the output of getting those invoice lines was too many for airflow dynamic task mapping to create mapped tasks for the next task. Of all the bookplate funds with funds in folio, this is the only one that failed. The log shows:
```
[2024-10-24, 07:35:48 UTC] {_client.py:1038} INFO - HTTP Request: POST https://okapi-test.stanford.edu/authn/login-with-expiry "HTTP/1.1 201 Created"
[2024-10-24, 07:35:48 UTC] {invoices.py:161} INFO - Getting paid invoice lines for 5f6e44fe-1129-4962-8406-0fcc60adf98d
[2024-10-24, 07:35:48 UTC] {_client.py:1038} INFO - HTTP Request: GET https://okapi-test.stanford.edu/invoice-storage/invoice-lines?query=%28fundDistributions%3D%3D%2A%225f6e44fe-1129-4962-8406-0fcc60adf98d%22%2A%29%20and%20invoiceLineStatus%3D%22Paid%22&limit=500&offset=0 "HTTP/1.1 200 OK"
[2024-10-24, 07:35:49 UTC] {_client.py:1038} INFO - HTTP Request: GET https://okapi-test.stanford.edu/invoice-storage/invoice-lines?query=%28fundDistributions%3D%3D%2A%225f6e44fe-1129-4962-8406-0fcc60adf98d%22%2A%29%20and%20invoiceLineStatus%3D%22Paid%22&limit=500&offset=500 "HTTP/1.1 200 OK"
[2024-10-24, 07:35:49 UTC] {_client.py:1038} INFO - HTTP Request: GET https://okapi-test.stanford.edu/invoice-storage/invoice-lines?query=%28fundDistributions%3D%3D%2A%225f6e44fe-1129-4962-8406-0fcc60adf98d%22%2A%29%20and%20invoiceLineStatus%3D%22Paid%22&limit=500&offset=1000 "HTTP/1.1 200 OK"
[2024-10-24, 07:35:50 UTC] {_client.py:1038} INFO - HTTP Request: GET https://okapi-test.stanford.edu/invoice-storage/invoice-lines?query=%28fundDistributions%3D%3D%2A%225f6e44fe-1129-4962-8406-0fcc60adf98d%22%2A%29%20and%20invoiceLineStatus%3D%22Paid%22&limit=500&offset=1500 "HTTP/1.1 200 OK"
[2024-10-24, 07:35:50 UTC] {_client.py:1038} INFO - HTTP Request: GET https://okapi-test.stanford.edu/invoice-storage/invoice-lines?query=%28fundDistributions%3D%3D%2A%225f6e44fe-1129-4962-8406-0fcc60adf98d%22%2A%29%20and%20invoiceLineStatus%3D%22Paid%22&limit=500&offset=2000 "HTTP/1.1 200 OK"
[2024-10-24, 07:35:50 UTC] {python.py:202} INFO - Done. Returned value was: [{'id': 'cd02c884-33bb-4ac8-9e02-006d10096ab4', 'adjustments': [{'description': 'TAX_9125', 'exportToAccounting': False, 'fundDistributions': [], 
<snip>
[2024-10-24, 07:35:51 UTC] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 452, in _execute_task
    _record_task_map_for_downstreams(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 932, in _record_task_map_for_downstreams
    raise UnmappableXComLengthPushed(value, max_map_length)
airflow.exceptions.UnmappableXComLengthPushed: unmappable return value length: 1706 > 1024
```
https://sul-libsys-airflow-dev.stanford.edu/log?dag_id=digital_bookplate_instances&task_id=invoice_lines_paid_on_fund&execution_date=2024-10-24T00:50:16.600813%2B00:00 

The fund name is LINDER.

**Comment by shelleydoljack** [comment]
Some options are to write out the too many things returned into a file or if it's too many, somehow break up the list into manageable chunks of 500 for mapping to tasks.
