### ISSUE TITLE
Determine if folio data import is concerned with the format of filenames

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#472]
One vendor includes parens in file names, currently there is a script to remove the parens as they caused an issue somewhere in the symphony pipeline. 

Determine if the folio data import has the same issue or if we can avoid file renaming.

**Comment by ndushay** [comment]
@justinlittman - I've been trying to follow the code, with partial success, and I'm wondering if the following is correct:

- we do the actual READ of the files in our vendor load airflow plugin ... that is, we send the _contents_ of the marc files as a payload in the POST request 
- this means that parens in the filenames are m00t, UNLESS they would affect the processing in our vendor_load plugin
  - multipart files?
  - reading them from within the context of the flask vendor-load plugin?

what is your take?

**Comment by justinlittman** [comment]
Are you trying to test file upload by user or FTP download from vendor?

**Comment by ndushay** [comment]
@justinlittman when vendor data is processed in prod now, with scripts and Symphony, Symphony barfs on parens.  Is that a m00t point for what we're doing?

**Comment by ndushay** [comment]
from Darsi:

![image](https://github.com/sul-dlss/libsys-airflow/assets/96775/5bc139c2-ad39-45d4-ba62-f020fd4d1061)

**Comment by ndushay** [comment]
On Justin's advice, I uploaded a file to airflow, using the Gobi full-bib approach (see https://sul-libsys-airflow-dev.stanford.edu/vendors/interface/18, from 2023-05-25) and it seems to have loaded (see https://folio-test.stanford.edu/data-import/job-summary/73e10f15-a790-46bb-9b7f-f74b5156f3ee)

**Comment by ndushay** [comment]
From https://docs.google.com/spreadsheets/d/1Z4mPTEZuw_YIqN2PCWy4BXbOzzi8zFAXqGwQBD0-It8, vendor CIBTC has parens in names:

- EUS91000_(20230207)_37.mrc
- EUS91005_(20230210)_212.mrc

**Comment by ndushay** [comment]
doing ftp from sul-libsys-airflow-dev:

```
libsys@sul-libsys-airflow-dev:~$ ftp -p 124.207.37.180 21
Connected to 124.207.37.180.
220 Microsoft FTP Service
Name (124.207.37.180:libsys): stanford
331 Password required for stanford.
Password: # see google sheet
230 User stanford logged in.
Remote system type is Windows_NT.
ftp> passive
Passive mode off.
ftp> passive
Passive mode on.
ftp> get EUS91006_(2020.12.28)_1.mrc
local: EUS91006_(2020.12.28)_1.mrc remote: EUS91006_(2020.12.28)_1.mrc
227 Entering Passive Mode (124,207,37,180,5,82).
125 Data connection already open; Transfer starting.
226 Transfer complete.
1921 bytes received in 0.00 secs (2.5445 MB/s)
ftp> exit
221  

libsys@sul-libsys-airflow-dev:~$ ls -l
total 108
drwxr-xr-x 3 libsys libsys  4096 Sep 19  2022  airflow
drwxr-xr-x 2 libsys libsys 77824 Apr  4 09:00  data
-rw-r--r-- 1 libsys libsys  1921 May 25 13:13 'EUS91006_(2020.12.28)_1.mrc'
drwxr-xr-x 3 libsys libsys  4096 Nov  2  2022  fixes
drwxr-xr-x 5 libsys libsys  4096 May 25 11:08  libsys-airflow
drwxr-xr-x 2 libsys libsys  4096 Apr 19  2022  mapping_files
drwxr-xr-x 6 libsys libsys  4096 Mar 15 08:09  virtual-env
```

on the remote:  `EUS91006_(2020.12.28)_1.mrc` (no quotes)
on our machine:  `'EUS91006_(2020.12.28)_1.mrc'` (single quotes)

I will now attempt to do this within python (but I expect it shells out to the os anyway)

**Comment by ndushay** [comment]
Notes on what I tried to do in python:

```
libsys@sul-libsys-airflow-dev:~$ python3
>>> from airflow.providers.ftp.hooks.ftp import FTPHook
>>> hook = FTPHook(ftp_conn_id="124.207.37.180")
>>> hook
<airflow.providers.ftp.hooks.ftp.FTPHook object at 0x7ff94907dca0>
>>> filename = "EUS91006_(2020.12.28)_1.mrc"
>>> hook.retrieve_file(filename, ".")
--- Logging error ---
Traceback (most recent call last):
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 400, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/secrets/metastore.py", line 36, in get_connection
    conn = session.query(Connection).filter(Connection.conn_id == conn_id).first()
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/libsys/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: connection
[SQL: SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted 
FROM connection 
WHERE connection.conn_id = ?
 LIMIT ? OFFSET ?]
[parameters: ('124.207.37.180', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/utils/log/colored_log.py", line 95, in format
    record = self._color_record_traceback(record)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/utils/log/colored_log.py", line 86, in _color_record_traceback
    self.color(self.log_colors, record.levelname) + record.exc_text + escape_codes['reset']
AttributeError: 'CustomTTYColoredFormatter' object has no attribute 'color'
Call stack:
  File "<stdin>", line 1, in <module>
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/providers/ftp/hooks/ftp.py", line 166, in retrieve_file
    conn = self.get_conn()
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/providers/ftp/hooks/ftp.py", line 60, in get_conn
    params = self.get_connection(self.ftp_conn_id)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 404, in get_connection_from_secrets
    log.exception(
Message: 'Unable to retrieve connection from secrets backend (%s). Checking subsequent secrets backend.'
Arguments: ('\x1b[1mMetastoreBackend\x1b[22m',)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/providers/ftp/hooks/ftp.py", line 166, in retrieve_file
    conn = self.get_conn()
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/providers/ftp/hooks/ftp.py", line 60, in get_conn
    params = self.get_connection(self.ftp_conn_id)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/libsys/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `124.207.37.180` isn't defined
```

**Comment by ndushay** [comment]
the surrounding quotes seem to a be problem;  I uploaded a file named `'filename(hasparens).mrc'` (with quotes) and it never appeared on https://folio-test.stanford.edu/data-import?direction=descending&sort=completedDate.  (I uploaded a diff file afterwards and it did appear.)

**Comment by aaron-collier** [comment]
Closing this as airflow does not seem to create these problematic characters.
