### ISSUE TITLE
unexpected error when running local instance

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/libsys-airflow#686]
discovered this when testing the `Dockerfile` change i added to #683, but this also happens to me on `main`, so i don't think it's the fault of that airflow version bump PR.

i ran into this by following the current README instructions for spinning up a local instance, which have worked for me without issue the last few weeks:
* pull the latest `main` and `poetry install`
* `docker compose build`
* `docker compose up airflow-init`
* `docker compose up`
* once everything is up and running, `poetry run dotenv run alembic upgrade head`
* try to `poetry run dotenv run bin/seed_vendors`

that last step gets me an error with a stack trace like:
```
% poetry run dotenv run bin/seed_vendors
Traceback (most recent call last):
  File "software_dev_projects/libsys-airflow/bin/seed_vendors", line 161, in <module>
    main(opts)
  File "software_dev_projects/libsys-airflow/bin/seed_vendors", line 93, in main
    vendor_load = VendorLoader(
  File "software_dev_projects/libsys-airflow/bin/seed_vendors", line 28, in __init__
    self.vendors = self._get_vendors()
  File "software_dev_projects/libsys-airflow/bin/seed_vendors", line 64, in _get_vendors
    vendor_result = self._folio_client.organizations
  File "software_dev_projects/libsys-airflow/bin/seed_vendors", line 33, in _folio_client
    return FolioClient(
  File "Library/Caches/pypoetry/virtualenvs/libsys-airflow-wuyX_Bf1-py3.10/lib/python3.10/site-packages/folioclient/FolioClient.py", line 26, in __init__
    self.login()
  File "Library/Caches/pypoetry/virtualenvs/libsys-airflow-wuyX_Bf1-py3.10/lib/python3.10/site-packages/folioclient/FolioClient.py", line 164, in login
    raise ValueError(f"HTTP {req.status_code}\t{req.text}")
ValueError: HTTP 403  <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

in the docker logs, i can also see errors like:
```
libsys-airflow-airflow-webserver-1  | [2023-06-21T18:42:53.476+0000] {plugins_manager.py:266} ERROR - Failed to import plugin /opt/airflow/libsys_airflow/plugins/folio/main.py
libsys-airflow-airflow-webserver-1  | Traceback (most recent call last):
libsys-airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/plugins_manager.py", line 258, in load_plugins_from_plugin_directory
libsys-airflow-airflow-webserver-1  |     loader.exec_module(mod)
libsys-airflow-airflow-webserver-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
libsys-airflow-airflow-webserver-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
libsys-airflow-airflow-webserver-1  |   File "/opt/airflow/libsys_airflow/plugins/folio/main.py", line 33, in <module>
libsys-airflow-airflow-webserver-1  |     healthcheck_view = Healthcheck()
libsys-airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/flask_appbuilder/baseviews.py", line 240, in __init__
libsys-airflow-airflow-webserver-1  |     if hasattr(getattr(self, attr_name), "_permission_name"):
libsys-airflow-airflow-webserver-1  |   File "/opt/airflow/libsys_airflow/plugins/folio/apps/healthcheck_view.py", line 39, in _folio_client
libsys-airflow-airflow-webserver-1  |     return FolioClient(
libsys-airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/folioclient/FolioClient.py", line 26, in __init__
libsys-airflow-airflow-webserver-1  |     self.login()
libsys-airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/folioclient/FolioClient.py", line 164, in login
libsys-airflow-airflow-webserver-1  |     raise ValueError(f"HTTP {req.status_code}\t{req.text}")
libsys-airflow-airflow-webserver-1  | ValueError: HTTP 403  <html>
libsys-airflow-airflow-webserver-1  | <head><title>403 Forbidden</title></head>
libsys-airflow-airflow-webserver-1  | <body>
libsys-airflow-airflow-webserver-1  | <center><h1>403 Forbidden</h1></center>
libsys-airflow-airflow-webserver-1  | <hr><center>nginx</center>
libsys-airflow-airflow-webserver-1  | </body>
libsys-airflow-airflow-webserver-1  | </html>
libsys-airflow-airflow-webserver-1  | 
libsys-airflow-airflow-webserver-1  | [2023-06-21T18:42:54.092+0000] {plugins.py:57} INFO - Registering plugin Flask
libsys-airflow-airflow-webserver-1  | [2023-06-21T18:42:54.092+0000] {flask.py:113} INFO - Initializing Honeybadger
libsys-airflow-airflow-webserver-1  | [2023-06-21T18:42:54.092+0000] {flask.py:143} INFO - Enabling auto-reporting exceptions
libsys-airflow-airflow-webserver-1  | [2023-06-21T18:42:54.093+0000] {flask.py:130} INFO - Honeybadger helper installed
libsys-airflow-airflow-webserver-1  | [2023-06-21T18:42:54.497+0000] {manager.py:504} INFO - Created Permission View: can read on DAGs

...

libsys-airflow-airflow-scheduler-1  | [2023-06-21T18:42:51.677+0000] {plugins_manager.py:266} ERROR - Failed to import plugin /opt/airflow/libsys_airflow/plugins/folio/main.py
libsys-airflow-airflow-scheduler-1  | Traceback (most recent call last):
libsys-airflow-airflow-scheduler-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/plugins_manager.py", line 258, in load_plugins_from_plugin_directory
libsys-airflow-airflow-scheduler-1  |     loader.exec_module(mod)
libsys-airflow-airflow-scheduler-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
libsys-airflow-airflow-scheduler-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
libsys-airflow-airflow-scheduler-1  |   File "/opt/airflow/libsys_airflow/plugins/folio/main.py", line 33, in <module>
libsys-airflow-airflow-scheduler-1  |     healthcheck_view = Healthcheck()
libsys-airflow-airflow-scheduler-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/flask_appbuilder/baseviews.py", line 240, in __init__
libsys-airflow-airflow-scheduler-1  |     if hasattr(getattr(self, attr_name), "_permission_name"):
libsys-airflow-airflow-scheduler-1  |   File "/opt/airflow/libsys_airflow/plugins/folio/apps/healthcheck_view.py", line 39, in _folio_client
libsys-airflow-airflow-scheduler-1  |     return FolioClient(
libsys-airflow-airflow-scheduler-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/folioclient/FolioClient.py", line 26, in __init__
libsys-airflow-airflow-scheduler-1  |     self.login()
libsys-airflow-airflow-scheduler-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/folioclient/FolioClient.py", line 164, in login
libsys-airflow-airflow-scheduler-1  |     raise ValueError(f"HTTP {req.status_code}\t{req.text}")
libsys-airflow-airflow-scheduler-1  | ValueError: HTTP 403  <html>
libsys-airflow-airflow-scheduler-1  | <head><title>403 Forbidden</title></head>
libsys-airflow-airflow-scheduler-1  | <body>
libsys-airflow-airflow-scheduler-1  | <center><h1>403 Forbidden</h1></center>
libsys-airflow-airflow-scheduler-1  | <hr><center>nginx</center>
libsys-airflow-airflow-scheduler-1  | </body>
libsys-airflow-airflow-scheduler-1  | </html>
```

and if i login, i can see DAGs and i can go to the vendor app, but i also see an error alert like:
<img width="1551" alt="Screen Shot 2023-06-21 at 11 44 21 AM" src="https://github.com/sul-dlss/libsys-airflow/assets/7741604/088d1c5d-31ff-47c9-816e-0ba03b1411ba">

**Comment by jmartin-sul** [comment]
d'oh, i bet this is me not being on the VPN... checking...

**Comment by jmartin-sul** [comment]
yup, reconnecting to VPN fixed, my fault, closing.
